export const tutorialWalkthroughIntro = {
  title: "Interactive Walkthrough",
  summary:
    "This coach drives a live hand and tells you exactly what to click, what each click does, and why it matters.",
  bullets: [
    "Follow the highlighted control each step.",
    "The game state stays real: chips, blinds, and turn order all apply.",
    "Use Skip Step if you already know a concept.",
  ],
};

export const tutorialWalkthroughSteps = [
  {
    id: "deal_hand_one",
    phase: "Setup",
    title: "Deal a fresh training hand",
    instruction: "Click Deal on the table header.",
    why: "A fresh hand resets action flow so your first decision is predictable.",
    bullets: [
      "Blinds are posted automatically.",
      "Your turn is forced to the opening seat for coaching.",
    ],
    mode: "table",
    targetSelector: "#newHandButton",
    clickKeys: ["deal"],
  },
  {
    id: "inspect_pot",
    phase: "Read The Table",
    title: "Check the pot and blind pressure",
    instruction: "Click the Pot badge to inspect where forced chips went.",
    why: "Before acting, you should read current pressure: pot size and blind stakes.",
    bullets: [
      "Pot starts with blind contributions.",
      "Blinds define minimum aggression each round.",
    ],
    mode: "table",
    targetSelector: "#potBadge",
    clickKeys: ["pot-badge"],
  },
  {
    id: "double_down",
    phase: "Pre-Action",
    title: "Use Double Down",
    instruction: "Click Double Down in the action row.",
    why: "Double Down commits extra chips now and locks your hand to its private cards.",
    bullets: [
      "Pre-Action only.",
      "You immediately receive a second private card.",
      "Future raises are locked out for your seat.",
    ],
    mode: "table",
    targetAction: "double",
    clickKeys: ["action-double"],
  },
  {
    id: "inspect_private_cards",
    phase: "Hand Reading",
    title: "Inspect your private cards",
    instruction: "Click your bottom player profile.",
    why: "After doubling, your private-card total drives every later decision.",
    bullets: [
      "Your total bubble now reflects two private cards.",
      "Standing locks community growth for your seat.",
    ],
    mode: "table",
    targetSelector: ".seat-bottom .profile-shell",
    clickKeys: ["hero-seat"],
  },
  {
    id: "wait_for_community",
    phase: "Round Flow",
    title: "Watch the first community reveal",
    instruction: "Wait while bots finish the round and the first community card appears.",
    why: "Community cards expand totals and reshape who is ahead.",
    bullets: [
      "Round order: Pre-Action, Action, Stage, Show, Caboose.",
      "Each reveal changes showdown math for active players.",
    ],
    mode: "table",
    targetSelector: "#communityCards",
    autoAdvance: "community-card",
  },
  {
    id: "open_hand_log",
    phase: "Review",
    title: "Open the hand log",
    instruction: "Use the menu dropdown and select Hands.",
    why: "The log lets you audit every bet, call, and reveal in sequence.",
    bullets: [
      "Use this to understand why the pot changed.",
      "Use this to confirm round transitions.",
    ],
    mode: "menu",
    panel: "tutorial",
    targetSelector: "#menuPanelSelect",
    autoAdvance: "panel-hands",
  },
  {
    id: "close_menu",
    phase: "Return",
    title: "Return to the table",
    instruction: "Click Close to go back to table controls.",
    why: "Live decisions are made from the table action row.",
    bullets: ["Switch between table and menu as needed during play."],
    mode: "menu",
    panel: "hands",
    targetSelector: "#closeMenu",
    clickKeys: ["close-menu"],
  },
  {
    id: "deal_hand_two",
    phase: "Action Drill",
    title: "Deal one more training hand",
    instruction: "Click Deal again.",
    why: "This second hand demonstrates the confirm flow for a standard Call.",
    bullets: [
      "Call requires explicit confirmation.",
      "You can still choose Stand or Cancel in confirm mode.",
    ],
    mode: "table",
    targetSelector: "#newHandButton",
    clickKeys: ["deal"],
  },
  {
    id: "click_call",
    phase: "Action Drill",
    title: "Choose Call",
    instruction: "Click Call in the action row.",
    why: "Call matches pressure without increasing the current bet.",
    bullets: ["Call enters the confirm decision layer."],
    mode: "table",
    targetAction: "call",
    clickKeys: ["action-call"],
  },
  {
    id: "confirm_call",
    phase: "Action Drill",
    title: "Confirm your call",
    instruction: "Click Confirm.",
    why: "Confirm commits chips and hands action to the next seat.",
    bullets: [
      "Stand: call now, lock total for later reveals.",
      "Cancel: back out and choose a different action.",
    ],
    mode: "table",
    targetAction: "confirm",
    clickKeys: ["confirm"],
  },
  {
    id: "complete",
    phase: "Complete",
    title: "Walkthrough complete",
    instruction: "Press Restart to run the tutorial again or continue playing normally.",
    why: "You have now practiced dealing, reading pressure, Double Down, logging, and Call-confirm flow.",
    bullets: [
      "Keep using the hand log to review key turns.",
      "Run the walkthrough again any time from this panel.",
    ],
    mode: "menu",
    panel: "tutorial",
  },
];
